apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-service-deployment.fullname" . }}-secret
  labels:
    {{- include "project-service-deployment.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets }}
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }} 