{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ .secretName }}
  duration: {{ .duration }}
  renewBefore: {{ .renewBefore }}
  dnsNames:
  {{- range .domains }}
    - {{ . }}
  {{- end }}
  issuerRef:
    name: {{ $.Values.issuer.name }}
    kind: {{ $.Values.issuer.type }}
{{- end }} 