{{- range .Values.ingressPatches }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $.Values.issuer.name }}
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
      {{- range $.Values.certificates }}
      {{- range .domains }}
        - {{ . }}
      {{- end }}
      {{- end }}
      secretName: {{ .secretName }}
{{- end }} 