{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "submissions-service-deployment.fullname" . }}-secret
  labels:
    {{- include "submissions-service-deployment.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }} 