apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-deployment.fullname" . }}-config
  labels:
    {{- include "auth-deployment.labels" . | nindent 4 }}
data:
  {{- if .Values.configData }}
  {{- range $key, $val := .Values.configData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }} 