apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "auth-deployment.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      kind: Rule
      services:
        - name: {{ include "auth-deployment.fullname" . }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: strip-prefix
          namespace: {{ .Release.Namespace }}
        - name: set-swagger-prefix
          namespace: {{ .Release.Namespace }} 