apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  replacePathRegex:
    regex: "^/user-api/(.*)"
    replacement: "/$1"
