{{- if .Values.configData -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-deployment.fullname" . }}-config
  labels:
    {{- include "front-deployment.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configData | nindent 2 }}
{{- end }} 