{{- if and .Values.ingress.enabled .Values.ingress.certSecretName -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "front-deployment.fullname" . }}-secure
  labels:
    {{- include "front-deployment.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`) && !PathPrefix(`/user-api/`)
      {{- range .paths }}
      {{- if eq .path "/" }}
      kind: Rule
      services:
        - name: {{ include "front-deployment.fullname" $ }}
          port: {{ $.Values.service.port }}
      {{- end }}
      {{- end }}
    {{- end }}
  tls:
    secretName: {{ .Values.ingress.certSecretName }}
{{- end }} 