apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-deployment.fullname" . }}-nginx-config
  labels:
    {{- include "front-deployment.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    server {
      listen 80;
      server_name _;

      index index.html;
      root /usr/share/nginx/html;

      error_log /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;

      client_max_body_size {{ .Values.configData.NGINX_CLIENT_MAX_BODY_SIZE | default "10m" }};

      location / {
        try_files $uri /index.html =404;
        
        proxy_connect_timeout {{ .Values.configData.NGINX_PROXY_CONNECT_TIMEOUT | default "60s" }};
        proxy_send_timeout {{ .Values.configData.NGINX_PROXY_SEND_TIMEOUT | default "60s" }};
        proxy_read_timeout {{ .Values.configData.NGINX_PROXY_READ_TIMEOUT | default "60s" }};
      }
    } 