{{- if and .Values.ingress.enabled .Values.ingress.certSecretName -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "front-deployment.fullname" . }}-redirect-https
  labels:
    {{- include "front-deployment.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }} 