{{- if and .Values.secrets (not .Values.existingSecret.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-deployment.fullname" . }}-secrets
  labels:
    {{- include "front-deployment.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }} 