apiVersion: v2
name: cert-deployment
description: A Helm chart for TLS certificate management on edulor.fr

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: cert-manager
    version: "1.12.x"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled 