# Cert-manager configuration
cert-manager:
  # Whether to install cert-manager as a dependency
  enabled: false
  installCRDs: false
  
  # Set global namespace for cert-manager
  global:
    leaderElection:
      namespace: cert-manager

# Certificate Issuer configuration
issuer:
  # Use Let's Encrypt production environment when true, staging when false
  production: true
  email: "admin@edulor.fr"
  # The name of the ClusterIssuer to create
  name: "letsencrypt"
  # The type of issuer (ClusterIssuer or Issuer)
  type: "ClusterIssuer"
  # Solver configuration for DNS01 or HTTP01 challenge
  solvers:
    - http01:
        ingress:
          class: traefik

# Certificate configuration
certificates:
  # List of certificates to be issued
  - name: "edulor-tls"
    # The list of domains the certificate should be valid for
    domains:
      - "edulor.fr"
    # Duration of the certificate (must use proper Kubernetes duration format)
    duration: "2160h"  # 90 days
    # Renewal time before expiry (must use proper Kubernetes duration format)
    renewBefore: "720h"  # 30 days
    # Secret name where the certificate will be stored
    secretName: "edulor-tls-cert"
    # Add additional labels to the certificate
    labels: {}
    # Add additional annotations to the certificate
    annotations: {}

# Ingress TLS configuration - disabled to avoid conflicts
ingressPatches: [] 